#pragma once
//  $Id: VTColors.h,v 1.5 2023/10/23 11:45:11 cvsuser Exp $
//
//  https://developer.mozilla.org/ko/docs/Web/CSS/color_value
//

#include "VTSupport.h"

namespace RGBColors {

#define XRGB__(r__,g__,b__) ((r__)|(g__ << 8)|(b__<<16))
    enum Color {
        black                   = XRGB__(0x00,0x00,0x00),
        silver                  = XRGB__(0xc0,0xc0,0xc0),
        gray                    = XRGB__(0x80,0x80,0x80),
        white                   = XRGB__(0xff,0xff,0xff),
        maroon                  = XRGB__(0x80,0x00,0x00),
        red                     = XRGB__(0xff,0x00,0x00),
        purple                  = XRGB__(0x80,0x00,0x80),
        fuchsia                 = XRGB__(0xff,0x00,0xff),
        green                   = XRGB__(0x00,0x80,0x00),
        lime                    = XRGB__(0x00,0xff,0x00),
        olive                   = XRGB__(0x80,0x80,0x00),
        yellow                  = XRGB__(0xff,0xff,0x00),
        navy                    = XRGB__(0x00,0x00,0x80),
        blue                    = XRGB__(0x00,0x00,0xff),
        teal                    = XRGB__(0x00,0x80,0x80),
        aqua                    = XRGB__(0x00,0xff,0xff),
        orange                  = XRGB__(0xff,0xa5,0x00),
        aliceblue               = XRGB__(0xf0,0xf8,0xff),
        antiquewhite            = XRGB__(0xfa,0xeb,0xd7),
        aquamarine              = XRGB__(0x7f,0xff,0xd4),
        azure                   = XRGB__(0xf0,0xff,0xff),
        beige                   = XRGB__(0xf5,0xf5,0xdc),
        bisque                  = XRGB__(0xff,0xe4,0xc4),
        blanchedalmond          = XRGB__(0xff,0xeb,0xcd),
        blueviolet              = XRGB__(0x8a,0x2b,0xe2),
        brown                   = XRGB__(0xa5,0x2a,0x2a),
        burlywood               = XRGB__(0xde,0xb8,0x87),
        cadetblue               = XRGB__(0x5f,0x9e,0xa0),
        chartreuse              = XRGB__(0x7f,0xff,0x00),
        chocolate               = XRGB__(0xd2,0x69,0x1e),
        coral                   = XRGB__(0xff,0x7f,0x50),
        cornflowerblue          = XRGB__(0x64,0x95,0xed),
        cornsilk                = XRGB__(0xff,0xf8,0xdc),
        crimson                 = XRGB__(0xdc,0x14,0x3c),
        cyan                    = XRGB__(0x00,0xff,0xff), // aqua
        darkblue                = XRGB__(0x00,0x00,0x8b),
        darkcyan                = XRGB__(0x00,0x8b,0x8b),
        darkgoldenrod           = XRGB__(0xb8,0x86,0x0b),
        darkgray                = XRGB__(0xa9,0xa9,0xa9),
        darkgreen               = XRGB__(0x00,0x64,0x00),
        darkgrey                = XRGB__(0xa9,0xa9,0xa9),
        darkkhaki               = XRGB__(0xbd,0xb7,0x6b),
        darkmagenta             = XRGB__(0x8b,0x00,0x8b),
        darkolivegreen          = XRGB__(0x55,0x6b,0x2f),
        darkorange              = XRGB__(0xff,0x8c,0x00),
        darkorchid              = XRGB__(0x99,0x32,0xcc),
        darkred                 = XRGB__(0x8b,0x00,0x00),
        darksalmon              = XRGB__(0xe9,0x96,0x7a),
        darkseagreen            = XRGB__(0x8f,0xbc,0x8f),
        darkslateblue           = XRGB__(0x48,0x3d,0x8b),
        darkslategray           = XRGB__(0x2f,0x4f,0x4f),
        darkslategrey           = XRGB__(0x2f,0x4f,0x4f),
        darkturquoise           = XRGB__(0x00,0xce,0xd1),
        darkviolet              = XRGB__(0x94,0x00,0xd3),
        deeppink                = XRGB__(0xff,0x14,0x93),
        deepskyblue             = XRGB__(0x00,0xbf,0xff),
        dimgray                 = XRGB__(0x69,0x69,0x69),
        dimgrey                 = XRGB__(0x69,0x69,0x69),
        dodgerblue              = XRGB__(0x1e,0x90,0xff),
        firebrick               = XRGB__(0xb2,0x22,0x22),
        floralwhite             = XRGB__(0xff,0xfa,0xf0),
        forestgreen             = XRGB__(0x22,0x8b,0x22),
        gainsboro               = XRGB__(0xdc,0xdc,0xdc),
        ghostwhite              = XRGB__(0xf8,0xf8,0xff),
        gold                    = XRGB__(0xff,0xd7,0x00),
        goldenrod               = XRGB__(0xda,0xa5,0x20),
        greenyellow             = XRGB__(0xad,0xff,0x2f),
        grey                    = XRGB__(0x80,0x80,0x80),
        honeydew                = XRGB__(0xf0,0xff,0xf0),
        hotpink                 = XRGB__(0xff,0x69,0xb4),
        indianred               = XRGB__(0xcd,0x5c,0x5c),
        indigo                  = XRGB__(0x4b,0x00,0x82),
        ivory                   = XRGB__(0xff,0xff,0xf0),
        khaki                   = XRGB__(0xf0,0xe6,0x8c),
        lavender                = XRGB__(0xe6,0xe6,0xfa),
        lavenderblush           = XRGB__(0xff,0xf0,0xf5),
        lawngreen               = XRGB__(0x7c,0xfc,0x00),
        lemonchiffon            = XRGB__(0xff,0xfa,0xcd),
        lightblue               = XRGB__(0xad,0xd8,0xe6),
        lightcoral              = XRGB__(0xf0,0x80,0x80),
        lightcyan               = XRGB__(0xe0,0xff,0xff),
        lightgoldenrodyellow    = XRGB__(0xfa,0xfa,0xd2),
        lightgray               = XRGB__(0xd3,0xd3,0xd3),
        lightgreen              = XRGB__(0x90,0xee,0x90),
        lightgrey               = XRGB__(0xd3,0xd3,0xd3),
        lightpink               = XRGB__(0xff,0xb6,0xc1),
        lightsalmon             = XRGB__(0xff,0xa0,0x7a),
        lightseagreen           = XRGB__(0x20,0xb2,0xaa),
        lightskyblue            = XRGB__(0x87,0xce,0xfa),
        lightslategray          = XRGB__(0x77,0x88,0x99),
        lightslategrey          = XRGB__(0x77,0x88,0x99),
        lightsteelblue          = XRGB__(0xb0,0xc4,0xde),
        lightyellow             = XRGB__(0xff,0xff,0xe0),
        limegreen               = XRGB__(0x32,0xcd,0x32),
        linen                   = XRGB__(0xfa,0xf0,0xe6),
        magenta                 = XRGB__(0xff,0x00,0xff), // fuchsia
        mediumaquamarine        = XRGB__(0x66,0xcd,0xaa),
        mediumblue              = XRGB__(0x00,0x00,0xcd),
        mediumorchid            = XRGB__(0xba,0x55,0xd3),
        mediumpurple            = XRGB__(0x93,0x70,0xdb),
        mediumseagreen          = XRGB__(0x3c,0xb3,0x71),
        mediumslateblue         = XRGB__(0x7b,0x68,0xee),
        mediumspringgreen       = XRGB__(0x00,0xfa,0x9a),
        mediumturquoise         = XRGB__(0x48,0xd1,0xcc),
        mediumvioletred         = XRGB__(0xc7,0x15,0x85),
        midnightblue            = XRGB__(0x19,0x19,0x70),
        mintcream               = XRGB__(0xf5,0xff,0xfa),
        mistyrose               = XRGB__(0xff,0xe4,0xe1),
        moccasin                = XRGB__(0xff,0xe4,0xb5),
        navajowhite             = XRGB__(0xff,0xde,0xad),
        oldlace                 = XRGB__(0xfd,0xf5,0xe6),
        olivedrab               = XRGB__(0x6b,0x8e,0x23),
        orangered               = XRGB__(0xff,0x45,0x00),
        orchid                  = XRGB__(0xda,0x70,0xd6),
        palegoldenrod           = XRGB__(0xee,0xe8,0xaa),
        palegreen               = XRGB__(0x98,0xfb,0x98),
        paleturquoise           = XRGB__(0xaf,0xee,0xee),
        palevioletred           = XRGB__(0xdb,0x70,0x93),
        papayawhip              = XRGB__(0xff,0xef,0xd5),
        peachpuff               = XRGB__(0xff,0xda,0xb9),
        peru                    = XRGB__(0xcd,0x85,0x3f),
        pink                    = XRGB__(0xff,0xc0,0xcb),
        plum                    = XRGB__(0xdd,0xa0,0xdd),
        powderblue              = XRGB__(0xb0,0xe0,0xe6),
        rosybrown               = XRGB__(0xbc,0x8f,0x8f),
        royalblue               = XRGB__(0x41,0x69,0xe1),
        saddlebrown             = XRGB__(0x8b,0x45,0x13),
        salmon                  = XRGB__(0xfa,0x80,0x72),
        sandybrown              = XRGB__(0xf4,0xa4,0x60),
        seagreen                = XRGB__(0x2e,0x8b,0x57),
        seashell                = XRGB__(0xff,0xf5,0xee),
        sienna                  = XRGB__(0xa0,0x52,0x2d),
        skyblue                 = XRGB__(0x87,0xce,0xeb),
        slateblue               = XRGB__(0x6a,0x5a,0xcd),
        slategray               = XRGB__(0x70,0x80,0x90),
        slategrey               = XRGB__(0x70,0x80,0x90),
        snow                    = XRGB__(0xff,0xfa,0xfa),
        springgreen             = XRGB__(0x00,0xff,0x7f),
        steelblue               = XRGB__(0x46,0x82,0xb4),
        tan                     = XRGB__(0xd2,0xb4,0x8c),
        thistle                 = XRGB__(0xd8,0xbf,0xd8),
        tomato                  = XRGB__(0xff,0x63,0x47),
        turquoise               = XRGB__(0x40,0xe0,0xd0),
        violet                  = XRGB__(0xee,0x82,0xee),
        wheat                   = XRGB__(0xf5,0xde,0xb3),
        whitesmoke              = XRGB__(0xf5,0xf5,0xf5),
        yellowgreen             = XRGB__(0x9a,0xcd,0x32),
        rebeccapurple           = XRGB__(0x66,0x33,0x99)
    };
#undef XRGB

    struct RGBName {
        const char *name;
        VTColor rgb;
    };

    const struct RGBName *names()
    {
        static struct RGBName names[] = {
#if defined(__WATCOMC__)
#define XRGBNAME__(name__)      { #name__, RGBColors::name__ }
#else
#define XRGBNAME__(name__)      { #name__, Color::name__ }
#endif
            XRGBNAME__(black               ),
            XRGBNAME__(silver              ),
            XRGBNAME__(gray                ),
            XRGBNAME__(white               ),
            XRGBNAME__(maroon              ),
            XRGBNAME__(red                 ),
            XRGBNAME__(purple              ),
            XRGBNAME__(fuchsia             ),
            XRGBNAME__(green               ),
            XRGBNAME__(lime                ),
            XRGBNAME__(olive               ),
            XRGBNAME__(yellow              ),
            XRGBNAME__(navy                ),
            XRGBNAME__(blue                ),
            XRGBNAME__(teal                ),
            XRGBNAME__(aqua                ),
            XRGBNAME__(orange              ),
            XRGBNAME__(aliceblue           ),
            XRGBNAME__(antiquewhite        ),
            XRGBNAME__(aquamarine          ),
            XRGBNAME__(azure               ),
            XRGBNAME__(beige               ),
            XRGBNAME__(bisque              ),
            XRGBNAME__(blanchedalmond      ),
            XRGBNAME__(blueviolet          ),
            XRGBNAME__(brown               ),
            XRGBNAME__(burlywood           ),
            XRGBNAME__(cadetblue           ),
            XRGBNAME__(chartreuse          ),
            XRGBNAME__(chocolate           ),
            XRGBNAME__(coral               ),
            XRGBNAME__(cornflowerblue      ),
            XRGBNAME__(cornsilk            ),
            XRGBNAME__(crimson             ),
            XRGBNAME__(cyan                ),
            XRGBNAME__(darkblue            ),
            XRGBNAME__(darkcyan            ),
            XRGBNAME__(darkgoldenrod       ),
            XRGBNAME__(darkgray            ),
            XRGBNAME__(darkgreen           ),
            XRGBNAME__(darkgrey            ),
            XRGBNAME__(darkkhaki           ),
            XRGBNAME__(darkmagenta         ),
            XRGBNAME__(darkolivegreen      ),
            XRGBNAME__(darkorange          ),
            XRGBNAME__(darkorchid          ),
            XRGBNAME__(darkred             ),
            XRGBNAME__(darksalmon          ),
            XRGBNAME__(darkseagreen        ),
            XRGBNAME__(darkslateblue       ),
            XRGBNAME__(darkslategray       ),
            XRGBNAME__(darkslategrey       ),
            XRGBNAME__(darkturquoise       ),
            XRGBNAME__(darkviolet          ),
            XRGBNAME__(deeppink            ),
            XRGBNAME__(deepskyblue         ),
            XRGBNAME__(dimgray             ),
            XRGBNAME__(dimgrey             ),
            XRGBNAME__(dodgerblue          ),
            XRGBNAME__(firebrick           ),
            XRGBNAME__(floralwhite         ),
            XRGBNAME__(forestgreen         ),
            XRGBNAME__(gainsboro           ),
            XRGBNAME__(ghostwhite          ),
            XRGBNAME__(gold                ),
            XRGBNAME__(goldenrod           ),
            XRGBNAME__(greenyellow         ),
            XRGBNAME__(grey                ),
            XRGBNAME__(honeydew            ),
            XRGBNAME__(hotpink             ),
            XRGBNAME__(indianred           ),
            XRGBNAME__(indigo              ),
            XRGBNAME__(ivory               ),
            XRGBNAME__(khaki               ),
            XRGBNAME__(lavender            ),
            XRGBNAME__(lavenderblush       ),
            XRGBNAME__(lawngreen           ),
            XRGBNAME__(lemonchiffon        ),
            XRGBNAME__(lightblue           ),
            XRGBNAME__(lightcoral          ),
            XRGBNAME__(lightcyan           ),
            XRGBNAME__(lightgoldenrodyellow),
            XRGBNAME__(lightgray           ),
            XRGBNAME__(lightgreen          ),
            XRGBNAME__(lightgrey           ),
            XRGBNAME__(lightpink           ),
            XRGBNAME__(lightsalmon         ),
            XRGBNAME__(lightseagreen       ),
            XRGBNAME__(lightskyblue        ),
            XRGBNAME__(lightslategray      ),
            XRGBNAME__(lightslategrey      ),
            XRGBNAME__(lightsteelblue      ),
            XRGBNAME__(lightyellow         ),
            XRGBNAME__(limegreen           ),
            XRGBNAME__(linen               ),
            XRGBNAME__(magenta             ),
            XRGBNAME__(mediumaquamarine    ),
            XRGBNAME__(mediumblue          ),
            XRGBNAME__(mediumorchid        ),
            XRGBNAME__(mediumpurple        ),
            XRGBNAME__(mediumseagreen      ),
            XRGBNAME__(mediumslateblue     ),
            XRGBNAME__(mediumspringgreen   ),
            XRGBNAME__(mediumturquoise     ),
            XRGBNAME__(mediumvioletred     ),
            XRGBNAME__(midnightblue        ),
            XRGBNAME__(mintcream           ),
            XRGBNAME__(mistyrose           ),
            XRGBNAME__(moccasin            ),
            XRGBNAME__(navajowhite         ),
            XRGBNAME__(oldlace             ),
            XRGBNAME__(olivedrab           ),
            XRGBNAME__(orangered           ),
            XRGBNAME__(orchid              ),
            XRGBNAME__(palegoldenrod       ),
            XRGBNAME__(palegreen           ),
            XRGBNAME__(paleturquoise       ),
            XRGBNAME__(palevioletred       ),
            XRGBNAME__(papayawhip          ),
            XRGBNAME__(peachpuff           ),
            XRGBNAME__(peru                ),
            XRGBNAME__(pink                ),
            XRGBNAME__(plum                ),
            XRGBNAME__(powderblue          ),
            XRGBNAME__(rosybrown           ),
            XRGBNAME__(royalblue           ),
            XRGBNAME__(saddlebrown         ),
            XRGBNAME__(salmon              ),
            XRGBNAME__(sandybrown          ),
            XRGBNAME__(seagreen            ),
            XRGBNAME__(seashell            ),
            XRGBNAME__(sienna              ),
            XRGBNAME__(skyblue             ),
            XRGBNAME__(slateblue           ),
            XRGBNAME__(slategray           ),
            XRGBNAME__(slategrey           ),
            XRGBNAME__(snow                ),
            XRGBNAME__(springgreen         ),
            XRGBNAME__(steelblue           ),
            XRGBNAME__(tan                 ),
            XRGBNAME__(thistle             ),
            XRGBNAME__(tomato              ),
            XRGBNAME__(turquoise           ),
            XRGBNAME__(violet              ),
            XRGBNAME__(wheat               ),
            XRGBNAME__(whitesmoke          ),
            XRGBNAME__(yellowgreen         ),
            XRGBNAME__(rebeccapurple       ),
#if defined(__WATCOMC__)
            { NULL, RGBColors::black }
#else
            { NULL, Color::black }
#endif            
#undef XRGBNAME
            };
        return names;
    }
};

//end